<script setup>
import imgSrc from "../assets/beaver.jpg";
</script>

<template>
  <n-space vertical align="center">
    <n-avatar class="flip-in-hor-bottom" round :size="72" :src="imgSrc" />
    <img id="home" src="../assets/home.png" />
  </n-space>
</template>
<style>
#home {
  width: 1000px;
  height: 500px;
}
.flip-in-hor-bottom {
  -webkit-animation: flip-in-hor-bottom 2s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    infinite alternate both;
  animation: flip-in-hor-bottom 2s cubic-bezier(0.25, 0.46, 0.45, 0.94) infinite
    alternate both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-9-2 20:46:1
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-in-hor-bottom
 * ----------------------------------------
 */
@-webkit-keyframes flip-in-hor-bottom {
  0% {
    -webkit-transform: rotateX(80deg);
    transform: rotateX(80deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0);
    transform: rotateX(0);
    opacity: 1;
  }
}
@keyframes flip-in-hor-bottom {
  0% {
    -webkit-transform: rotateX(80deg);
    transform: rotateX(80deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0);
    transform: rotateX(0);
    opacity: 1;
  }
}
</style>
